---
- name: Setup Ansible Inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add VM2 to Inventory
      add_host:
        name: VM2
        groups: webservers
        ansible_host: 10.0.0.238
        ansible_ssh_user: sajal

    - name: Add VM3 to Inventory
      add_host:
        name: VM3
        groups: webservers
        ansible_host: 10.0.0.56
        ansible_ssh_user: sajal

- name: Undeploy Webserver
  hosts: webservers
  become: yes
  tasks:
    - name: Remove Apache Webserver
      apt:
        name: apache2
        state: absent
      when: webserver_state == 'undeployed'
